### ISSUE TITLE
can not install libignition dependency

### ISSUE THREAD

**Issue by CAI006** [ros-controls/ros2_control_ci#135]
![Screenshot from 2024-09-03 16-57-25](https://github.com/user-attachments/assets/4fc28b4b-f040-44e1-8470-c8f5a7719413)
Have tried different ways to solve, but didnt work.

**Comment by CAI006** [comment]
![image](https://github.com/user-attachments/assets/7f0157ba-db1a-4fce-86f8-043ccfe2a8ad)

**Comment by christophfroehlich** [comment]
On which linux version are you working on? Can it be that you upgraded your distro with gazebo being installed already?

**Comment by CAI006** [comment]
Already solve the problem by uninstall and then install gazebo. It is caused by the conflict of different version of gazebo.
________________________________
发件人: Christoph Fr?hlich ***@***.***>
发送时间: 2024年9月5日 15:11
收件人: ros-controls/ros2_control_ci ***@***.***>
抄送: #CAI HAONAN# ***@***.***>; Author ***@***.***>
主题: Re: [ros-controls/ros2_control_ci] can not install libignition dependency (Issue #135)


On which linux version are you working on? Can it be that you upgraded your distro with gazebo being installed already?

―
