### ISSUE TITLE
Check for failed stage in ici and open issue only in certain ones

### ISSUE THREAD

**Issue by fmauch** [ros-controls/ros2_control_ci#28]
As mentioned in https://github.com/ros-controls/ros2_control_demos/issues/457 it might be good to check where things actually fail. If builds fail due to some temporary resolution problems there's probably no need in opening a new issue for that.

**Comment by christophfroehlich** [comment]
https://github.com/ros-controls/ros2_control_ci/pull/21#issuecomment-1971187544

**Comment by christophfroehlich** [comment]
@fmauch it seems that this works fine now. Should we add this to the source build workflow as well?

**Comment by christophfroehlich** [comment]
That's true, but if no one is checking the outcome of the scheduled build we might skip the workflow at all :grin:
