### ISSUE TITLE
ICI workflow @ humble is flaky 

### ISSUE THREAD

**Issue by christophfroehlich** [ros-controls/ros2_control_ci#34]
Why does it fail here? 👀 @saikishor 
https://github.com/ros-controls/ros2_control_ci/actions/runs/8304468913/job/22730143420

    [ RUN      ] TestLoadController.multi_ctrls_test_type_in_param
    ...
    [INFO] [1710554585.628199404] [test_controller_manager]: Configuring controller 'ctrl_1'
    terminate called after throwing an instance of 'std::runtime_error'
      what():  Can not get command interface configuration until the controller is configured.

**Comment by christophfroehlich** [comment]
@fmauch can this be the result of https://github.com/ros-controls/ros2_control_ci/issues/33? (code from master from the compatibiltiy-workflow sneaked into humble workspace)

**Comment by christophfroehlich** [comment]
Caching is now fixed (I hope) but the issue persists https://github.com/ros-controls/ros2_control_ci/actions/runs/8747264205/job/24005451302

**Comment by christophfroehlich** [comment]
See #62

**Comment by christophfroehlich** [comment]
and see #63 (happens on main as well as on testing)

**Comment by saikishor** [comment]
Once the jazzy stuff is done, I hope I'll have time to take a look at this

**Comment by christophfroehlich** [comment]
Reported in https://github.com/ros-controls/ros2_control/issues/1368
